name: Deploy docs

on: [push]

jobs:
    deploy:
        runs-on: ubuntu-22.04
        permissions:
            contents: write
        concurrency:
            group: ${{ github.workflow }}-${{ github.ref }}
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Setup PNPM
              run: npm install --global pnpm

            - name: Install dependencies
              run: pnpm install

            - name: Build
              run: pnpm doc

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              if: ${{ github.ref == 'refs/heads/main' }}
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./docs
